### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by anders-s** [MrVallentin/PyLua#1]
I'm interested in this project. Would it be possible to release the source for what you have currently implemented, even if it's incomplete?

**Comment by kieranz** [comment]
I’m guessing this is for roblox.

**Comment by anders-s** [comment]
lol, no. i was interested in transpiling an object-definition language implemented in python into lua
it isn't necessary anymore, i opted for a different approach

**Comment by oilaba** [comment]
I want to see the source code, where is it?
